import React from "react";
import { useSelector } from "react-redux";
import jsPDF from "jspdf";
import "jspdf-autotable";
import { format } from "date-fns";
import "./transactions.css";

const Transactions =()=>
{
  const transactions=useSelector((state)=>state.transactions)||[];
  const currentUser=useSelector((state)=>state.user);

  const filteredTransactions=transactions.filter(
    (txn)=>txn.senderId===currentUser?._id
  );

  const data=filteredTransactions.length>0?filteredTransactions:[];

  const generateInvoice=(txn)=> 
{
    const img=new Image();
    img.src="/logo.png";
    img.onload=()=>
    {
      const doc=new jsPDF();

      doc.addImage(img,"PNG",20,10,30,15);

      doc.setFillColor(20,60,69);
      doc.rect(0,0,210,30,"F");
      doc.setFontSize(18);
      doc.setTextColor(255);
      doc.setFont("helvetica","bold");
      doc.text("PayPanel - Transaction Invoice",105,18,null,null,"center");

      doc.setTextColor(33,33,33);
      doc.setFontSize(12);
      doc.setFont("helvetica","normal");

      const yStart=40;
      const lineSpacing=10;

      doc.text(`Invoice ID: ${txn.id}`, 20, yStart);
      doc.text(`Date: ${format(new Date(txn.date), "PPP")}`, 20, yStart + lineSpacing);
      doc.text(`Receiver: ${txn.receiver}`, 20, yStart + lineSpacing * 2);
      doc.text(`Amount: INR ${txn.amount}`, 20, yStart + lineSpacing * 3);

      doc.autoTable({
        startY:yStart+lineSpacing*5,
        head:[["Field", "Details"]],
        body:[["Invoice ID", txn.id], ["Receiver", txn.receiver], ["Amount", `INR ${txn.amount}`], ["Date", format(new Date(txn.date), "PPP")],],
        theme:"striped",
        headStyles:{fillColor:[20,60,69],textColor:255,fontSize:12,},
        styles:{fontSize:11,cellPadding:6,},
        margin:{ left:20,right:20},
      });

      const pageHeight=doc.internal.pageSize.height;
      doc.setFontSize(10);
      doc.setTextColor(120);
      doc.text("Generated by PayPanel • contact: ayushagrawal.5288@gmail.com • Thank you for trusting us!",105,pageHeight - 10,null,null,"center");
      doc.save(`invoice_${txn.id}.pdf`);
    };
    img.onerror=()=>
    {
      alert("Failed to load logo.Make sure /logo.png exists in the public folder.");
    };
  };

  return (
    <div className="transaction-wrapper">
      <div className="transaction-card">
        <h2 className="transaction-title">🧾 Transaction History</h2>
        {data.length===0?(<p className="transaction-empty">No transactions yet.</p>):
        (
          <div className="table-scroll">
            <table className="transaction-table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Receiver</th>
                  <th>Amount</th>
                  <th>Date</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {data.map((txn, index) => (
                  <tr key={txn.id}>
                    <td>{index + 1}</td>
                    <td>{txn.receiver}</td>
                    <td>INR {txn.amount}</td>
                    <td>{format(new Date(txn.date), "PPP")}</td>
                    <td>
                      <button onClick={() => generateInvoice(txn)} className="download-button"> Download</button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};

export default Transactions;
